name: "Artifact Submit Action"
author: "Ace Archive"
description: >
  A GitHub action for submitting artifacts to Ace Archive.
inputs:
  upload:
    description: >
      If `true`, validate the syntax of the submission files and upload files to
      S3. If `false, just validate.
    required: true
    default: "false"
  path:
    description: >
      The path of the directory in the git repository to read the submission
      JSON files from.
    required: true
  base_url:
    description: >
      The base URL that artifact files will be hosted from.
    required: true
  s3_endpoint:
    description: >
      The S3 endpoint URL. This is only required when using a non-AWS
      implementation of the S3 API.
  s3_bucket:
    description: >
      The name of the S3 bucket.
    required: true
  s3_prefix:
    description: >
      A prefix to add to all S3 object keys. You can also think of this like the
      name of a "directory" in the bucket.
  s3_region:
    description: >
      The AWS region name for S3.
    required: true
  s3_access_key_id:
    description: >
      The access key ID for S3.
    required: true
  s3_secret_access_key:
    description: >
      The secret access key for S3.
    required: true
  cloudflare_account_id:
    description: >
      The Cloudflare account ID for Workers KV.
    required: true
  cloudflare_api_token:
    description: >
      The secret Cloudflare API token to authenticate with Workers KV.
    required: true
  kv_namespace_id:
    description: >
      The namespace ID for Cloudflare Workers KV.
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
