name: "Artifact Submit Action"
author: "Ace Archive"
description: >
  A GitHub action for submitting artifacts to Ace Archive.
inputs:
  mode:
    description: >
      The mode to operate in, either `validate` or `upload`.

      In `validate` mode, the syntax of the submission files is validated and
      the hashes and media types of files without one are computed and added to
      the submission JSON in the job's local clone of the repo.

      In `upload` mode, files are downloaded, their hashes are validated, and
      they are uploaded to S3.
    required: true
  path:
    description: >
      The path of the directory in the git repository to read the submission
      JSON files from.
    required: true
  base_url:
    description: >
      The base URL that artifact files will be hosted from.
    required: true
  base_ref:
    description: >
      The ref of the base branch, used to determine which files have changed in
      this PR.
    required: true
  s3_endpoint:
    description: >
      The S3 endpoint URL. This is only required when using a non-AWS
      implementation of the S3 API.
  s3_bucket:
    description: >
      The name of the S3 bucket.
    required: true
  s3_prefix:
    description: >
      A prefix to add to all S3 object keys. You can also think of this like the
      name of a "directory" in the bucket.
  s3_region:
    description: >
      The AWS region name for S3.
    required: true
  s3_access_key_id:
    description: >
      The access key ID for S3.
    required: true
  s3_secret_access_key:
    description: >
      The secret access key for S3.
    required: true
  submission_worker_domain:
    description: >
      The domain name of the submission-worker instance used to upload metadata
      to the database.
    required: true
  submission_worker_secret:
    description: >
      The secret used to authenticate with submission-worker in order to upload
      metadata to the database.
    required: true
outputs:
  artifacts:
    description: >
      A JSON array containing the artifact metadata generated from each
      submission file.

runs:
  using: "node16"
  main: "dist/index.js"
