name: "Artifact Submit Action"
author: "Ace Archive"
description: >
  A GitHub action for submitting artifacts to Ace Archive.
inputs:
  repo:
    description: >
      The GitHub repository to write the generated JSON file to.
    required: true
  path:
    description: >
      The path in the repository to write the generated JSON file to.
    required: true
    default: "artifacts/"
  baseUrl:
    description: >
      The base URL that artifact files will be hosted from.
    required: true
  endpoint:
    description: >
      The S3 endpoint URL. This is only required when using a non-AWS
      implementation of the S3 API.
  bucket:
    description: >
      The name of the S3 bucket.
    required: true
  prefix:
    description: >
      A prefix to add to all S3 object keys. You can also think of this like the
      name of a "directory" in the bucket.
  region:
    description: >
      The AWS region name for S3.
    required: true
  access_key_id:
    description: >
      The access key ID for S3.
    required: true
  secret_access_key:
    description: >
      The secret access key for S3.
    required: true
outputs:
  name:
    description: >
      The published IPNS name.
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: tag
  color: blue
